# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14eEPzvaac55w1v9C0fjdjaprLkB4TGXT
"""

import pandas as pd

# dosyalari yüklüyoruz ve isimlerini eşleştiriyoruz
files = ['Aligned.csv', 'Flocking.csv', 'Grouped.csv']


df_list = []
for f in files:
    try:
        # ilk boş satırı atlıyoruz
        temp_df = pd.read_csv(f, skiprows=[0], encoding='latin1')
        df_list.append(temp_df)
        print(f"{f} başarıyla okundu. Boyut: {temp_df.shape}")
    except Exception as e:
        print(f"{f} okunurken hata oluştu: {e}")

# tabloda birleştirme
df = pd.concat(df_list, ignore_index=True)

# boşlukları temizleme
df.columns = df.columns.str.strip()

print("\n BİRLEŞTİRME TAMAMLANDI ")
print(f"Toplam Satır Sayısı: {df.shape[0]}")
print(f"Toplam Sütun Sayısı: {df.shape[1]}")

target_column = df.columns[-1]
# veriyi inceleme
print(f"Hedef Sütun Adı: {target_column}")
print("-" * 30)
print("Sınıf Dağılımı:")
print(df[target_column].value_counts())
print("-" * 30)

# rastgele 5 örenği inceleyelim
display(df.sample(5).T)

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

#veriyi hazırlama
target_column = df.columns[-1]
X = df.iloc[:, :-1]
y = df.iloc[:, -1]


X = X.apply(pd.to_numeric, errors='coerce').fillna(0)

# PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Model eğitimi knn kullanımı
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

#  görselleştirme
y_pred = model.predict(X_test)

print(" PROJE SONUÇLARI ")
print(f"Başarı Oranı (Accuracy): %{accuracy_score(y_test, y_pred)*100:.5f}")
print("\nSınıflandırma Raporu:")
print(classification_report(y_test, y_pred, digits=5))

# hata matrisi
plt.figure(figsize=(6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.title('Hata Matrisi (Confusion Matrix) - KNN')
plt.xlabel('Tahmin Edilen')
plt.ylabel('Gerçek Değer')
plt.show()

# pca kümeleme grafiği
plt.figure(figsize=(10, 6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='coolwarm', alpha=0.5)
plt.title('PCA ile Sürü Davranışı Analizi')
plt.colorbar(label='Sürü Durumu')
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# geri kalan tüm modelleri de analiz ediyoruz

modeller = {
    "Rastgele Orman": RandomForestClassifier(random_state=42),
    "Karar Ağacı": DecisionTreeClassifier(random_state=42),
    "K-En Yakın Komşu": KNeighborsClassifier(n_neighbors=5),
    "Lojistik Regresyon": LogisticRegression(max_iter=1000, random_state=42),
    "Basit Bayes": GaussianNB(),
    "YSA (Yapay Sinir Ağları)": MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
}

#döngü ile modelleri çalıştırıyoruz
for isim, model in modeller.items():
    print(f"\n{'='*50}")
    print(f"🟢 ŞU AN ÇALIŞAN MODEL: {isim}")
    print(f"{'='*50}")

    # modeli eğit
    model.fit(X_train, y_train)

    # modeli test etme
    y_pred = model.predict(X_test)

    # sonuçları ve raporu yazdır
    acc = accuracy_score(y_test, y_pred)
    print(f"Genel Başarı Oranı (Accuracy): %{acc*100:.5f}\n")
    print("Tabloya Yazılacak Değerler İçin Sınıflandırma Raporu:")
    print(classification_report(y_test, y_pred, digits=5))

    # her bir algoritma için ayrı ayrı hata matrisi
    plt.figure(figsize=(6, 4))

    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
    plt.title(f'{isim} - Hata Matrisi')
    plt.xlabel('Tahmin Edilen')
    plt.ylabel('Gerçek Değer')
    plt.show()

print("\n🚀 TÜM MODELLERİN TESTİ VE GRAFİK ÇİZİMLERİ TAMAMLANDI!")